# Generated by Django 3.0.1 on 2020-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('created',)},
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('messanger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Messanger')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Subject')),
            ],
        ),
    ]
