# Generated by Django 3.0.1 on 2020-01-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200118_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
